# "NOTE: Please allow a couple of minutes for the GitLab application to start."
# "Port: 10080. user: root. default pw: 5iveL!fe or changed to 12345678"

version: '2.1'
services:
    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - ./jenkins_home:/var/jenkins_home
        networks:
            dev-network:
                ipv4_address: 172.18.0.2

    jenkins-slave:
        image: evarga/jenkins-slave
        container_name: jenkins-slave
        networks:
            dev-network:
                ipv4_address: 172.18.0.4

    postgres:
        image: postgres
        container_name: postgresql-ci
        environment:
            - DB_NAME=gitlabhq_production
        volumes: 
            - ./postgres:/var/lib/postgresql
    redis:
        image: redis:alpine
        container_name: redis-ci
        volumes:
            - ./redis:/data
    gitlab:
        image: gitlab/gitlab-ce
        container_name: gitlab-ci
        links:
            - postgres
            - redis
        ports:
            - "10443:443"
            - "10022:22"
            - "10080:80"
        environment:
            - GITLAB_PORT=10080
            - GITLAB_SSH_PORT=10022
        volumes:
            - ./gitlab/config:/etc/gitlab
            - ./gitlab/logs:/var/log/gitlab
            - ./gitlab/data:/var/opt/gitlab
        networks:
            dev-network:
                ipv4_address: 172.18.0.3

networks:
    dev-network:
        external: true