version: '2'
services:
    jenkins:
        image: jenkins
        container_name: jenkins_1
        volumes:
            - "./jenkins_data:/var/jenkins_home"
        ports: 
            - "50000:50000"
            - "8080:8080"
